/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Help */

#ifndef _Included_Help
#define _Included_Help
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Help
 * Method:    jump
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Help_jump
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
